services:
  - type: web
    name: audovenko-mdw-apits
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DB_PATH
        value: /app/data/app.db
